add_newline = true

format = """
 $directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = """$cmd_duration"""

[directory]
style = "bold blue"
truncation_length = 4
truncation_symbol = "…/"

[character]
success_symbol = " [\\$](bold green) "
error_symbol = " [\\$](bold red) "

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
min_time = 2_000
format = "[󱎫 $duration](bold yellow) "

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
